<a href="https://colab.research.google.com/github/vamsikandula03/pytorch-learning/blob/main/Linear_regression_using_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
from torch.utils import data


In [3]:
pip install d2l

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.7/111.7 kB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 41.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 53.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 59.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 15.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.4/123.4 kB 14.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 10.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 28.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.5/93.5 kB 12.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 20.6 MB/s eta 0:00:00
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 3.1.2
    Uninstalling pyparsing-3.1.2:
      Successfully uninstalled pyparsing-3.1.2
  Attempting uninstall:

In [2]:
from d2l import torch as d21

In [4]:
true_w=torch.tensor([2,-3.4])
true_b=4.2
features,labels=d21.synthetic_data(true_w,true_b,1000)

In [5]:
def load_array(data_arrays,batch_size,is_train=True):
  dataset=data.TensorDataset(*data_arrays)
  return data.DataLoader(dataset,batch_size,shuffle=is_train)

In [6]:
batch_size=10
data_iter=load_array((features,labels),batch_size)

Defining the model

In [7]:
from torch import nn

In [8]:
net=nn.Sequential()

In [10]:
net.add_module('linear_layer', nn.Linear(2, 1))

In [11]:
net

Sequential(
  (linear_layer): Linear(in_features=2, out_features=1, bias=True)
)

In [12]:
net2=nn.Sequential(nn.Linear(2,1)) #same as before just to clarify

In [13]:
net2

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
)

model parameters


In [14]:
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)

tensor([0.])

loss function

In [15]:
loss=nn.MSELoss()

In [18]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[ 0.0040, -0.0186]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


optimization

In [19]:
trainer=torch.optim.SGD(net.parameters(),lr=0.03)

training

In [24]:
num_epoches=100
for i in range(num_epoches):
  for X,y in data_iter:
    l=loss(net(X),y)
    trainer.zero_grad()
    l.backward()
    trainer.step()
  l=loss(net(features),labels)
  print("epoch: "+str(i)+"  loss: "+str(float(l)))

epoch: 0  loss: 0.00010289595957146958
epoch: 1  loss: 0.0001029437335091643
epoch: 2  loss: 0.00010279278649250045
epoch: 3  loss: 0.00010414921416668221
epoch: 4  loss: 0.00010292328079231083
epoch: 5  loss: 0.00010262760770274326
epoch: 6  loss: 0.00010266406025039032
epoch: 7  loss: 0.00010274221131112427
epoch: 8  loss: 0.00010389420640422031
epoch: 9  loss: 0.00010299962013959885
epoch: 10  loss: 0.00010281817958457395
epoch: 11  loss: 0.00010330811346648261
epoch: 12  loss: 0.00010361858585383743
epoch: 13  loss: 0.0001032550644595176
epoch: 14  loss: 0.00010259924601996318
epoch: 15  loss: 0.0001033155494951643
epoch: 16  loss: 0.00010337756248190999
epoch: 17  loss: 0.00010302002920070663
epoch: 18  loss: 0.00010299789573764428
epoch: 19  loss: 0.00010363779438193887
epoch: 20  loss: 0.00010255207598675042
epoch: 21  loss: 0.00010319831926608458
epoch: 22  loss: 0.00010293904051650316
epoch: 23  loss: 0.00010298905544914305
epoch: 24  loss: 0.00010283963638357818
epoch: 25  lo

In [25]:
w=net[0].weight.data
b=net[0].bias.data

print("original")
print("true_w: ")
print(true_w)
print("true_b")
print(true_b)
print("model estimation")
print("w")
print(w)
print("b")
print(b)

original
true_w: 
tensor([ 2.0000, -3.4000])
true_b
4.2
model estimation
w
tensor([[ 2.0005, -3.4006]])
b
tensor([4.2002])
